Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "public_network", type:"static", ip: "192.168.0.10"
  config.vm.provision "docker" do |docker|
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install nfs-common
    sudo docker pull networkboot/dhcpd
    sudo docker pull ubuntu/bind9
    sudo docker pull httpd:2.4
    sudo docker pull fauria/vsftpd
    sudo docker pull itsthenetwork/nfs-server-alpine
    sudo chmod +x script.sh
  SHELL
  end
end
